### PR TITLE
Add usage with TypeScript section

### PR DESCRIPTION
**Pull request by Glazy**
Related to #9

### CODE REVIEW

**Comment by silvenon** [comment]
Thanks so much for this! I really want to fix this rather than make people do this. If I don't come up with the solution in a few days, I'll merge 😄

**Comment by Glazy** [comment]
Hey @silvenon 👋🏻 Did you manage to find a fix yet? :+1:

**Comment by silvenon** [comment]
@Glazy thanks for pinging, I will try to come up with something today 😄

**Comment by silvenon** [comment]
When I was testing my plugin with TypeScript, it turned out I only needed to use the correct order, gatsby-plugin-typescript **before** `gatsby-plugin-linaria`. This is how my plugin worked anyway, I only documented that behavior now. If you also needed to add `babel.config.js` like in #9, can you create a small demo for me reproducing the problem?

**Pull request closed without merging**
